precmd:
- cmds:
  - cmd: ""
preinit:
- cmds:
  - cmd: ""
preconf:
- cmds:
  - cmd: ""
postinit:
- cmds:
  - cmd: ""
postfini:
- cmds:
  - cmd: ""
nodes:
- name: ""
  type: ""
  net_base: ""
  image: ""
  interfaces:
  - name: ""
    type: ""
    args: ""
    addr: ""
    label: ""
  sysctls: []
switches:
- name: ""
  interfaces:
  - name: ""
    type: ""
    args: ""
    addr: ""
node_configs:
- name: ""
  cmds:
  - cmd: ""
test:
- name: ""
  cmds:
  - cmd: ""
